### ISSUE TITLE
No "exports" main defined

### ISSUE THREAD

**Issue by CooperEdmunds** [ipld/js-car#138]
Getting the following error when executing the .js outputted from npx tsc:
`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /[path]/node_modules/@ipld/car/package.json
    at new NodeError (node:internal/errors:400:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:641:13)
    at resolveExports (node:internal/modules/cjs/loader:538:36)
    at Module._findPath (node:internal/modules/cjs/loader:607:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1025:27)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/[path]/out/handleMessage.js:14:15) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}`

I'm importing like this:
`import { CarReader } from '@ipld/car'`

My tsconfig is as follows:
`{
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "target": "es6",
    "outDir": "./out",
    "sourceMap": true,
    "strict": true,
    "noImplicitAny": true,
    "moduleResolution": "node",
    "baseUrl": ".",
    "paths": {
      "*": ["node_modules/*", "src/types/*"]
    },
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules", "**/*.spec.ts"]
}`

I'm sure I'm making a stupid mistake but am lost. Any help would be greatly appreciated.

**Comment by rvagg** [comment]
I think your `"module": "commonjs"` in tsconfig is the problem. "esnext" might be more appropriate: https://www.typescriptlang.org/tsconfig#module

The problem you're having is that you're hitting the Node.js `require` path, which won't work the current version of `@ipld/car` (it will on an older version if you wind back a semver-major version or two - which is also OK to do if you don't need newer features). We only export ES Modules now, not CommonJS, so `import` rather than `require` works and your TypeScript compiler is turning your `import` into a `require` because you're telling it to use `"commonjs"`.

**Comment by deanshelton913** [comment]
Oh i see, it DOES work when i add "type":"module" to my package.json file.. but i can not do that to my larger project i need this in. We integrate many other packages and this is the only one that throws this issue, it would be great to support both, vs. making client choose a module structure

**Comment by rvagg** [comment]
Sorry, but we dropped dual publishing a while back. If it's critical, then you can roll back to `^4` and get both esm and cjs entrypoints: https://unpkg.com/browse/@ipld/car@4.1.6/package.json. The switch was the main reason for the semver-major bump to `5` and you're not missing out on much by not going beyond `^4`. There will be new features added going forward, but nothing critical was fixed (yet) that's not available to `^4` users.
