### ISSUE TITLE
dag-json support for CarReader.fromBytes

### ISSUE THREAD

**Issue by agsola** [ipld/js-car#141]
I'm trying to get a CarReader for a encoded dag-json, but when trying this:

```
      import { encode } from '@ipld/dag-json'

...


      let encoded = encode(objToStore);
      let carReader = await CarReader.fromBytes(encoded);
```

I'm getting this error:
`IPFS Error: CBOR decode error: too many terminals, data makes no sense`

Is it possible to create a CAR or CarReader from a dag-json?

**Comment by rvagg** [comment]
> Is it possible to create a CAR or CarReader from a dag-json?

No, what `CarReader.fromBytes` is doing is decoding a _CAR_ format, but you're giving it as _DAG-JSON_ format blob, the two things don't compare. The reason you're seeing a CBOR error is that it's trying to decode the CAR header, which is DAG-CBOR encoded.

So this all depends on what you're actually trying to achieve. Perhaps you want to wrap a DAG-JSON block in a CAR format? In which case, you'll have to do that with a CAR writer, collect the bytes from that, then decode them to retrieve the block. The utility of that is pretty limited though. `import { decode } from '@ipld/dag-json'` is probably easier to decode a DAG-JSON block.
