### ISSUE TITLE
Proposal: make CarReader API sync

### ISSUE THREAD

**Issue by Gozala** [ipld/js-car#74]
From what I can tell `CarReader` is unnecessarily async, most methods are just accessors into the pre-computed data

https://github.com/ipld/js-car/blob/master/lib/reader-browser.js#L33-L140

I am guessing it is for the compatibility with `IndexedReader`. If so I would like to propose doing what we did here
https://github.com/multiformats/js-multiformats/issues/159

**Comment by rvagg** [comment]
IIRC it's async for the `IndexedReader` case as well as other future read modes - particularly interesting are the modes enabled by CARv2 which let us read index data off disk.

tbh there may also be hold-over API concerns improperly inherited from the original js-datastore-car code.

I don't think I mind if you want to an optionally-sync interface that could be feature/type detected. Is this for performance concerns? I wonder if we just did away with the unncessary `async`s in reader-browser.js (and did some hackery with types to make tsc happy) would those concerns go away with the VM collapsing the unnecessary `await`s?

**Comment by rvagg** [comment]
@Gozala have you had a chance to think further about this? I'm interested in (a) whether you're interested in this for perf or other reasons and (b) whether you're interested in coming up with a fix or change to accommodate.

**Comment by Gozala** [comment]
> @Gozala have you had a chance to think further about this? I'm interested in (a) whether you're interested in this for perf or other reasons and (b) whether you're interested in coming up with a fix or change to accommodate.

@rvagg sorry for not responding sooner, last comment slipped notifications.

I want the sync API mostly because I want to create multicodec which produces data in CAR format. Given that multicodec interface is sync I need a sync interface for decode / encode.

So far I have punned on this via nasty hackery https://github.com/web3-storage/ucanto/blob/main/src/car.js#L82-L99 I would however love to remove that hack and instead land a patch that could provide a sync interface.


> would those concerns go away with the VM collapsing the unnecessary awaits?

If there was no cost to awaiting I suppose it would no longer matter if APIs are sync or async since we could essentially turn anything to async and do obsolete awaits. That said I think it is worth taking extra time in not introducing unnecessary async APIs, it not only harms performance but also makes it more tricky to work with WASM.

**Comment by rvagg** [comment]
@Gozala do you have time to do some work to make this happen? I'd prefer optionally-sync, but it's not a strict requirement if that's difficult. I just want to leave space for a common interface with alternative read modes; particularly with full CARv2 coming at some point. But this particular use really doesn't need to be async and the awaits can be removed.

**Comment by hugomrdias** [comment]
this can be closed now right ?
